package com.example.network.model.response.coinlist

data class CoinDetailResponse(
    val id: Int,
    val issuePrice: Any,
    val issuePriceUsed: Any,
    val issueDate: Any,
    val source: Any,
    val name: String,
    val fullName: String,
    val localFullName: String,
    val cmcUniqueId: Int,
    val logo: String,
    val symbol: String,
    val circulatingSupply: Long,
    val maxSupply: Long?,
    val totalSupply: Long,
    val volume: Double,
    val volumeGlobal: Any,
    val rank: Int,
    val dayChange: Double,
    val dayChangeAmount: Double,
    val marketCap: Double,
    val price: Double,
    val mapperName: String,
    val tags: List<String>,
    val tagInfos: List<CoinTagInfoResponse>,
    val url: Any,
    val imageUrl: Any,
    val explorerUrls: Any,
    val website: Any,
    val tradeUrl: Any,
    val slug: String,
    val baseAsset: Any,
    val quoteAsset: Any
)
